### PR TITLE
Workaround for possible memory-hogging DoS

### PR DESCRIPTION
**Pull request by onebone**

### CODE REVIEW

**Comment by cr0sh** [comment]
Great job :D

**Comment by onebone** [comment]
@cr0sh :+1:

**Comment by shoghicp** [comment]
This will stop working after 1000 normal joins, and never be reset. I have a better workaround over a local branch.

Remember that this only happens if the source doesn't protect you against spoofed ips

**Comment by willowmaster66** [comment]
Not sure but the count never gets down. Why not? Or doesn't it matter?

**Pull request closed without merging**
